redmine:
  restart: always
  build: redmine
  volumes_from:
    - data
  volumes:
    - redmine/.email.secret:/var/local/environment/vars
  ports:
    - "80:80"
  env_file:
    - .redmine.secret
  links:
    - mysql
    - postfix

mysql:
  restart: always
  image: sameersbn/mysql
  volumes_from:
    - data
  volumes:
    - backup/:/var/local/backup/
  env_file:
    - .mysql.secret

postfix:
  restart: always
  image: eeacms/postfix:eionet
  env_file:
    - .postfix.secret

data:
  build: data
  user: 1000
