redmine:
  restart: always
  build: redmine
  volumes_from:
    - data
  volumes:
    - redmine/.email.secret:/var/local/environment/vars
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "8888:80"
  env_file:
    - .redmine.secret
    - redmine.env
  links:
    - mysql
    - postfix
    - memcached

mysql:
  restart: always
  image: sameersbn/mysql
  volumes_from:
    - data
  volumes:
    - backup/:/var/local/backup/
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .mysql.secret
    - mysql.env

postfix:
  restart: always
  image: eeacms/postfix:eionet
  volumes:
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .postfix.secret

memcached:
  restart: always
  image: eeacms/memcached
  env_file:
    - .memcached.secret
    - memcached.env
  ports:
    - "11211:11211"

data:
  build: data
  user: "1000"
