version: "2"
services:
  redmine:
    image: eeacms/redmine:latest

  postfix:
    image: eaudeweb/mailtrap
    ports:
      - "8081:80"

  logspout:
    environment:
      SYSLOG_HOSTNAME: "taskman.devecs.eea.europa.eu"