redmine:
  restart: always
  image: eeacms/redmine:3.3.1
  volumes_from:
    - data
  volumes:
    - ./.email.secret:/var/local/environment/vars:z
    - /etc/localtime:/etc/localtime:ro
    - ./plugins:/install_plugins:z
  ports:
    - "8889:8080"
  env_file:
    - .redmine.secret
    - redmine.env
  links:
    - mysql
    - postfix
    - memcached

mysql:
  restart: always
  image: mysql:5.7.10
  volumes_from:
    - mysql_data
  volumes:
    - ./backup/:/var/local/backup/:z
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .mysql.secret
    - mysql.env

postfix:
  restart: always
  image: eeacms/postfix:eionet
  volumes:
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .postfix.secret

memcached:
  restart: always
  image: eeacms/memcached
  env_file:
    - .memcached.secret
    - memcached.env
  ports:
    - "11211:11211"

data:
  image: busybox
  volumes:
    - /home/redmine/data
    - /home/redmine/redmine/github
  command: ['chown', '-v', '-R', '500:500', '/home/redmine/data', '/home/redmine/redmine/github']

mysql_data:
  image: busybox
  volumes:
    - /var/lib/mysql
  #command: ['tail', '-f', '/dev/null']
 
