redmine:
  restart: always
  image: docker.io/eeacms/redmine:3.1.1-3.2
  volumes_from:
    - data
  volumes:
    - ./.email.secret:/var/local/environment/vars:z
    - /etc/localtime:/etc/localtime:z
  ports:
    - "8889:8080"
  env_file:
    - .redmine.secret
    - redmine.env
  links:
    - mysql
    - postfix
    - memcached

mysql:
  restart: always
  image: sameersbn/mysql
  volumes_from:
    - data
  volumes:
    - ./backup/:/var/local/backup/:z
    - /etc/localtime:/etc/localtime:z
  env_file:
    - .mysql.secret
    - mysql.env

postfix:
  restart: always
  image: eeacms/postfix:eionet
  volumes:
    - /etc/localtime:/etc/localtime:z
  env_file:
    - .postfix.secret

memcached:
  restart: always
  image: eeacms/memcached
  env_file:
    - .memcached.secret
    - memcached.env
  ports:
    - "11211:11211"

data:
  build: data
  user: "1000"
