version: "2"
services:
  redmine:
    restart: always
    image: eeacms/redmine:3.3-1.1
    ports:
    - "8889:8080"
    volumes:
    - ./.email.secret:/var/local/environment/vars:z
    - ./plugins:/install_plugins:z
    - data:/home/redmine/data
    - github:/home/redmine/redmine/github
    environment:
      TZ: "Europe/Copenhagen"
      NGINX_ENABLED: "false"
      NGINX_MAX_UPLOAD_SIZE: "100M"
      NGINX_WORKERS: "auto"
      UNICORN_TIMEOUT: "600"
      SMTP_ENABLED: "true"
      SMTP_HOST: "postfix"
      SMTP_PORT: "25"
      DB_ADAPTER: "mysql2"
      DB_HOST: "mysql"
      DB_PORT: "3306"
    env_file:
    - .redmine.secret
    depends_on:
    - mysql
    - postfix
    - memcached
  mysql:
    restart: always
    image: mysql:5.7.10
    volumes:
    - ./backup:/var/local/backup:z
    - mysql:/var/lib/mysql
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .mysql.secret
  postfix:
    restart: always
    image: eeacms/postfix:eionet
    env_file:
    - .postfix.secret
    environment:
      TZ: "Europe/Copenhagen"
  memcached:
    restart: always
    image: image: memcached:1.4.33-alpine
    ports:
    - "11211:11211"

volumes:
  data:
  github:
  mysql:
