version: "2"
services:
  redmine:
    image: eeacms/redmine:3.3-2.0
    ports:
    - "8080:3000"
    volumes:
      - ./.email.secret:/var/local/environment/vars:z
      - ./plugins:/install_plugins:z
      - redmine-files:/usr/src/redmine/files
      - redmine-tmp:/usr/src/redmine/tmp
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-github:/var/local/redmine/github/
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .redmine.secret
    - redmine.env
    - development.env
    depends_on:
    - mysql
    - postfix
    - memcached

  mysql:
    image: mysql:5.7.10
    volumes:
    - ./backup/:/var/local/backup/:z
    - /etc/localtime:/etc/localtime:ro
    - mysql-data:/var/lib/mysql
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .mysql.secret
    - mysql.env

  postfix:
    image: eeacms/postfix:2.10-3.1
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .postfix.secret

  memcached:
    image: memcached:1.4.36
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"
    env_file:
    - .memcached.secret
    - memcached.env

volumes:
  redmine-files:
  redmine-tmp:
  redmine-github:
  redmine-plugins:
  mysql-data: