redmine:
  restart: allways
  build: redmine
  volumes_from:
    - data
  ports:
    - "80:80"
  env_file:
    - .redmine.secret
  links:
    - mysql

mysql:
  restart: allways
  image: sameersbn/mysql
  volumes_from:
    - data
  volumes:
    - backup/:/var/local/backup/
  env_file:
    - .mysql.secret

data:
  build: data
  user: 1000
