version: "2"
services:
  redmine:
    image: eeacms/redmine:3.3-2.0
    restart: always
    labels:
      eu.europa.eionet.taskman: "yes"
    ports:
    - "8080:3000"
    volumes:
      - ./.email.secret:/var/local/environment/vars:z
      - ./plugins:/install_plugins:z
      - redmine-files:/usr/src/redmine/files
      - redmine-tmp:/usr/src/redmine/tmp
      - redmine-plugins:/usr/src/redmine/plugins
      - redmine-github:/var/local/redmine/github/
    environment:
      TZ: "Europe/Copenhagen"
      NGINX_ENABLED: "false"
      NGINX_MAX_UPLOAD_SIZE: "100M"
      NGINX_WORKERS: "auto"
      UNICORN_TIMEOUT: "600"
      SMTP_ENABLED: "true"
      SMTP_HOST: "postfix"
      SMTP_PORT: "25"
    env_file:
    - .redmine.secret
    depends_on:
    - mysql
    - postfix
    - memcached

  mysql:
    image: mysql:5.7.10
    restart: always
    labels:
      eu.europa.eionet.taskman: "yes"
    volumes:
    - ./backup/:/var/local/backup/:z
    - /etc/localtime:/etc/localtime:ro
    - mysql-data:/var/lib/mysql
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .mysql.secret

  postfix:
    image: eeacms/postfix:2.10-3.1
    restart: always
    labels:
      eu.europa.eionet.taskman: "yes"
    environment:
      TZ: "Europe/Copenhagen"
    env_file:
    - .postfix.secret

  memcached:
    image: memcached:1.4.36
    restart: always
    labels:
      eu.europa.eionet.taskman: "yes"
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"

  logspout:
    image: gliderlabs/logspout:v3.1
    restart: always
    command: 'syslog://logcentral.eea.europa.eu:1514?filter.label=eu.europa.eionet.taskman:yes'
    environment:
      SYSLOG_HOSTNAME: "taskman.eionet.europa.eu"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redmine-files:
  redmine-tmp:
  redmine-github:
  redmine-plugins:
  mysql-data:
